# Federated Learning Configuration

# Data Configuration
data:
  dataset: 'cifar10'  # Options: 'mnist', 'cifar10'
  num_clients: 5
  samples_per_client: 8000
  iid: True    # Set to True for IID data, False for non-IID data

# Model Configuration
model:
  name: 'cifar_cnn'  # Options: 'cnn [1,28,28]', 'cifar_cnn[3,32,32]'
  input_shape: [3, 32, 32]  # [channels, height, width]
  num_classes: 10

# Training Configuration
training:
  global_rounds: 10
  local_epochs: 5
  batch_size: 64
  learning_rate: 0.01
  momentum: 0.9

# Server Configuration
server:
  aggregation: 'fedavg'  # Options: 'fedavg', 'fedprox'
  fraction_clients: 1.0  # Fraction of clients to select each round

# Client Configuration
client:
  optimizer: 'sgd'  # Options: 'sgd', 'adam'
  criterion: 'crossentropy'
  # FedProx configuration
  fedprox:
    enabled: False  # Set to True to enable FedProx
    mu: 0.01  # Proximal term coefficient
